name: Deploy Hugo site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          submodules: true  # Required if theme is a submodule

      # Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build the site
      - name: Build
        run: hugo --minify

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # Test that deployed pages are reachable
      - name: Test Deployed Site
        run: |
          SITE="https://markdmh.uk"
          PAGES=("/" "/about/" "/services/" "/contact/")
          MAX_RETRIES=3
          RETRY_DELAY=10

          for PAGE in "${PAGES[@]}"; do
            echo "Checking page: $SITE$PAGE"
            SUCCESS=0
            for i in $(seq 1 $MAX_RETRIES); do
              STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$SITE$PAGE")
              if [ "$STATUS" -eq 200 ]; then
                echo "✅ $PAGE reachable (HTTP $STATUS)"
                SUCCESS=1
                break
              else
                echo "Attempt $i failed (HTTP $STATUS), retrying in $RETRY_DELAY seconds..."
                sleep $RETRY_DELAY
              fi
            done
            if [ "$SUCCESS" -ne 1 ]; then
              echo "❌ $PAGE not reachable after $MAX_RETRIES attempts"
              exit 1
            fi
          done
