name: Deploy Hugo site to apex domain

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for worktree push

      # Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Deploy built site to main root without deleting source
      - name: Deploy to main root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add a temporary worktree for root deployment
          git worktree add deploy-temp main

          # Copy Hugo public/ content into worktree
          cp -r public/* deploy-temp/
          echo "markdmh.uk" > deploy-temp/CNAME

          # Commit and push changes from worktree
          cd deploy-temp
          git add --all
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Automated Hugo deploy"
            git push origin main
          else
            echo "No changes to deploy"
          fi

          # Cleanup worktree
          cd ..
          git worktree remove deploy-temp
