name: Deploy Hugo site

# Trigger workflow on push to main
on:
  push:
    branches:
      - main

# Required permissions for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build Hugo site
      - name: Build Hugo site
        run: |
          echo "=== Building Hugo site ==="
          hugo --minify --verbose
          echo "=== Hugo build finished ==="

      # Add CNAME for apex domain
      - name: Add CNAME
        run: echo "markdmh.uk" > public/CNAME

      # Upload public/ folder as artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      # Deploy via GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
